name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Install External Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          pip install pytest Cython
          sudo apt install libcairo2-dev pkg-config python3-dev
          sudo apt-get install libpango1.0-dev


      - name: Install External Dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install pango
          brew install cairo

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
